name: FitTest
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altgraph=0.17.2=pyhd8ed1ab_0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.10.8=h5b45459_0
  - future=0.18.2=py310h5588dad_4
  - libffi=3.4.2=h8ffe710_5
  - libzlib=1.2.11=h8ffe710_1013
  - macholib=1.14=pyh9f0ad1d_1
  - openssl=3.0.0=h8ffe710_2
  - pefile=2021.9.3=pyhd8ed1ab_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pyinstaller=4.8=py310h3cefddf_0
  - pyinstaller-hooks-contrib=2021.5=pyhd8ed1ab_0
  - pyserial=3.4=py_2
  - pysimplegui=4.55.1=pyhd8ed1ab_0
  - python=3.10.1=hcf16a7b_2_cpython
  - python_abi=3.10=2_cp310
  - pywin32=303=py310he2412df_0
  - pywin32-ctypes=0.2.0=py310h5588dad_1004
  - setuptools=60.2.0=py310h5588dad_0
  - sqlite=3.37.0=h8ffe710_0
  - tk=8.6.11=h8ffe710_1
  - tzdata=2021e=he74cb21_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_1
prefix: C:\Users\jjudg\anaconda3\envs\FitTest
